version: '3'
services: 
  webapp:
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports: 
      - 5000:5000
    volumes:
      - api: ./api_publicidade 
    command: "~/api/start1.sh ""
 